Q1 = "SELECT COUNT(ID) FROM Movie WHERE year= 2002 AND name LIKE 'Ha%' AND rank >2;"
Q2 = "SELECT MAX(rank) FROM Movie WHERE year IN (1983,1994) AND name LIKE 'Autom%';"
Q3 = "SELECT COUNT(ID) FROM Actor WHERE GENDER = 'M' AND (fname LIKE '%ei' OR lname LIKE 'ei%');"
Q4 = "SELECT AVG(rank) as average_rank_of_movies FROM Movie WHERE year IN(1993,1995,2000)AND rank>=4.2;"
Q5 = "SELECT SUM(rank) FROM Movie WHERE year BETWEEN 1981 AND 1994 AND  name LIKE '%Hary%' AND rank<9;"
Q6 = "SELECT MIN(year) FROM Movie WHERE rank = 5 ;"
Q7 = "SELECT COUNT(*) FROM Actor WHERE GENDER = 'F' or fname = lname;"
Q8 = "SELECT DISTINCT(fname) FROM Actor WHERE lname LIKE '%ei' ORDER BY fname LIMIT 100;"
Q9 = "SELECT id,name,year AS movie_title  FROM Movie WHERE  year in(2001,2002,2005,2006) LIMIT 25 OFFSET 10;"
Q10 = "SELECT DISTINCT(lname) FROM Director WHERE fname in('Yeud','Wolf','Vicky') ORDER BY lname LIMIT 5;"