Q1 = "SELECT * FROM Movies ORDER BY rank DESC LIMIT 10;"
Q2 = "SELECT * FROM Movies ORDER BY rank DESC LIMIT 10 OFFSET 10;"
Q3 = "SELECT name FROM Movies Where year>2016;"
Q4 = "SELECT name FROM Movies Where rank<1.1;"
Q5 = "SELECT name FROM Movies Where year in(2006,2007,2005);"
Q6 = "SELECT NAME,year FROM Movies WHERE name = 'harry potter';"
Q7 = "SELECT * FROM Actor WHERE first name='Christin' AND last name !='Watson';" 
Q8 = "SELECT * FROM Actor WHERE first name='Christin' AND last name ='Watson';" 
Q9 = "SELECT name FROM Movies WHERE year = 1990 AND rank = 5;"
Q10 = "SELECT * FROM Actor WHERE first name='Christin'  OR last name ='Watson';" 
Q11 = "SELECT name FROM Movies WHERE year In (2007,2008,2009);"
Q12 = "SELECT DISTINCT year FROM Movies ORDER BY year"
Q13 = "SELECT * FROM Actor WHERE first_name = 'Christin' or last name = 'Watson' ORDER BY first name LIMIT 10' "