Q1 = "select count(id) from movie where year<2000;"
Q2 = "select avg(rank) from movie where year = 1991;"
Q3 = "select min(rank) from movie where year = 1991;"
Q4 = "select fname,lname from (actor inner join cast on id== pid)where mid=27;"
Q5 = "select count(a.id) from (actor inner join cast on id ==pid)as a where a.fname = 'Jon' and a.lname='Dough';"
Q6 = "select name from movie where name like 'young latin girls%' and year between 2003 and 2006;"
Q10 = "select gender,count(id) from actor group by gender order by gender;"
Q7 = "select d.fname,d.lname from(director as d inner join moviedirector as md on d.id==md.did)inner join movie as m on m.id ==md.mid where m.name like 'Star Trek%';" 
#Q9 = " select fname,lname from director where id in (73615,79174,7599,9077,11122,45406) order by fname ,lname DESC;"
#Q8 = "select name from movie where id in (52,164576) order by name;"
Q11 = "select distinct(a.name),b.name,a.rank,a.year from(movie as a inner join movie as b on a.year == b.year and a.rank ==b.rank and a.name!= b.name) order by a.name limit 100"
Q12 = "select a.fname, m.year,m.rank From(actor as  a inner join cast as c on a.id==c.pid) inner join movie as m on m.id==c.mid order by a.fname ASC ,m.year DESC limit 100;"
Q13 = "select a.fname,d.fname,avg(m.rank) as score From(((actor as  a inner join cast as c on a.id==c.pid) inner join movie as m on m.id==c.mid)inner join moviedirector as md on md.mid==m.id)inner join director as d on d.id==md.did group by a.id,d.id having count(m.id)>=5  order by avg(m.rank) DEsc,d.fname ASC,a.fname DESC limit 100;"
Q9 = "select director.fname,director.lname from movie inner join moviedirector on  `movie`.id==`moviedirector`.mid inner join director on `moviedirector`.did == `director`.id where year =2001 group by did having count(`movie`.id)>=4 order by fname ,lname desc;"
Q8 = "select m.name From(((actor as  a inner join cast as c on a.id==c.pid) inner join movie as m on m.id==c.mid)inner join moviedirector as md on md.mid==m.id)inner join director as d on d.id==md.did where a.fname='Jackie (I)' and a.lname= 'Chan' and d.fname ='Jackie (I)' and d.lname='Chan';"