Q1 = "SELECT * FROM Movie ORDER BY rank DESC LIMIT 10;"
Q2 = "SELECT * FROM Movie ORDER BY rank DESC LIMIT 10 OFFSET 10;"
Q3 = "SELECT name FROM Movie Where year>2004;"
Q4 = "SELECT name FROM Movie Where rank<1.1;"
Q5 = "SELECT * FROM Movie Where year in(2004,2005,2006);"
Q6 = "SELECT name,year FROM Movie WHERE name LIKE 'Harry%';"
Q7 = "SELECT * FROM Actor WHERE fname='Christin' AND lname !='Watson';" 
Q8 = "SELECT * FROM Actor WHERE fname='Woody' AND lname ='Watson';" 
Q9 = "SELECT name FROM Movie WHERE year = 1990 AND rank = 5;"
Q10 = "SELECT * FROM Actor WHERE fname='Christin' AND lname ='Watson';" 
#Q11 = "SELECT name FROM Movie WHERE year In (2003,2004,2005);"
Q11 = "SELECT name FROM Movie WHERE year BETWEEN 2003 AND 2005"
Q12 = "SELECT DISTINCT year FROM Movie ORDER BY year"
#Q13 = "SELECT * FROM Actor WHERE (fname = 'Christin' OR lname = 'Watson') AND (GENDER='M') ORDER BY fname LIMIT 10;"
Q13 = "SELECT * FROM Actor WHERE (fname = 'Christin' OR lname = 'Watson') ORDER BY GENDER DESC LIMIT 10"
